import 'package:country_pickers/country.dart';

final List<Country> countryList = [
  Country(
    isoCode: "AF",
    phoneCode: "93",
    name: "Afeganistão",
    iso3Code: "AFG",
  ),
  Country(
    isoCode: "AL",
    phoneCode: "355",
    name: "Albânia",
    iso3Code: "ALB",
  ),
  Country(
    isoCode: "DZ",
    phoneCode: "213",
    name: "Argélia",
    iso3Code: "DZA",
  ),
  Country(
    isoCode: "AS",
    phoneCode: "1-684",
    name: "Samoa Americana",
    iso3Code: "ASM",
  ),
  Country(
    isoCode: "AD",
    phoneCode: "376",
    name: "Andorra",
    iso3Code: "AND",
  ),
  Country(
    isoCode: "AO",
    phoneCode: "244",
    name: "Angola",
    iso3Code: "AGO",
  ),
  Country(
    isoCode: "AI",
    phoneCode: "1-264",
    name: "Anguilla",
    iso3Code: "AIA",
  ),
  Country(
    isoCode: "AQ",
    phoneCode: "672",
    name: "Antártica",
    iso3Code: "ATA",
  ),
  Country(
    isoCode: "AG",
    phoneCode: "1-268",
    name: "Antigua e Barbuda",
    iso3Code: "ATG",
  ),
  Country(
    isoCode: "AR",
    phoneCode: "54",
    name: "Argentina",
    iso3Code: "ARG",
  ),
  Country(
    isoCode: "AM",
    phoneCode: "374",
    name: "Armênia",
    iso3Code: "ARM",
  ),
  Country(
    isoCode: "AW",
    phoneCode: "297",
    name: "Aruba",
    iso3Code: "ABW",
  ),
  Country(
    isoCode: "AU",
    phoneCode: "61",
    name: "Austrália",
    iso3Code: "OFF",
  ),
  Country(
    isoCode: "AT",
    phoneCode: "43",
    name: "Áustria",
    iso3Code: "AUT",
  ),
  Country(
    isoCode: "AZ",
    phoneCode: "994",
    name: "Azerbaijão",
    iso3Code: "AZE",
  ),
  Country(
    isoCode: "BS",
    phoneCode: "1-242",
    name: "Bahamas",
    iso3Code: "BHS",
  ),
  Country(
    isoCode: "BH",
    phoneCode: "973",
    name: "Bahrain",
    iso3Code: "BHR",
  ),
  Country(
    isoCode: "BD",
    phoneCode: "880",
    name: "Bangladesh",
    iso3Code: "BGD",
  ),
  Country(
    isoCode: "BB",
    phoneCode: "1-246",
    name: "Barbados",
    iso3Code: "BRB",
  ),
  Country(
    isoCode: "BY",
    phoneCode: "375",
    name: "Belarus",
    iso3Code: "BLR",
  ),
  Country(
    isoCode: "BE",
    phoneCode: "32",
    name: "Bélgica",
    iso3Code: "BEL",
  ),
  Country(
    isoCode: "BZ",
    phoneCode: "501",
    name: "Belize",
    iso3Code: "BLZ",
  ),
  Country(
    isoCode: "BJ",
    phoneCode: "229",
    name: "Benin",
    iso3Code: "BEN",
  ),
  Country(
    isoCode: "BM",
    phoneCode: "1-441",
    name: "Bermuda",
    iso3Code: "BMU",
  ),
  Country(
    isoCode: "BT",
    phoneCode: "975",
    name: "Butão",
    iso3Code: "BTN",
  ),
  Country(
    isoCode: "BO",
    phoneCode: "591",
    name: "Bolívia, Estado Plurinacional de",
    iso3Code: "BOL",
  ),
  Country(
    isoCode: "BA",
    phoneCode: "387",
    name: "Bósnia e Herzegovina",
    iso3Code: "BIH",
  ),
  Country(
    isoCode: "BW",
    phoneCode: "267",
    name: "Botswana",
    iso3Code: "BWA",
  ),
  Country(
    isoCode: "BV",
    phoneCode: "47",
    name: "Ilha Bouvet",
    iso3Code: "BVT",
  ),
  Country(
    isoCode: "BR",
    phoneCode: "55",
    name: "Brasil",
    iso3Code: "BRA",
  ),
  Country(
    isoCode: "IO",
    phoneCode: "246",
    name: "Território Britânico do Oceano Índico",
    iso3Code: "IOT",
  ),
  Country(
    isoCode: "BN",
    phoneCode: "673",
    name: "Brunei Darussalam",
    iso3Code: "BRN",
  ),
  Country(
    isoCode: "BG",
    phoneCode: "359",
    name: "Bulgária",
    iso3Code: "BGR",
  ),
  Country(
    isoCode: "BF",
    phoneCode: "226",
    name: "Burkina Faso",
    iso3Code: "BFA",
  ),
  Country(
    isoCode: "BI",
    phoneCode: "257",
    name: "Burundi",
    iso3Code: "BDI",
  ),
  Country(
    isoCode: "KH",
    phoneCode: "855",
    name: "Camboja",
    iso3Code: "KHM",
  ),
  Country(
    isoCode: "CM",
    phoneCode: "237",
    name: "Camarões",
    iso3Code: "CMR",
  ),
  Country(
    isoCode: "CA",
    phoneCode: "1",
    name: "Canadá",
    iso3Code: "CAN",
  ),
  Country(
    isoCode: "CV",
    phoneCode: "238",
    name: "Cabo Verde",
    iso3Code: "CPV",
  ),
  Country(
    isoCode: "BQ",
    phoneCode: "599",
    name: "Holanda caribenha",
    iso3Code: "BES",
  ),
  Country(
    isoCode: "KY",
    phoneCode: "1-345",
    name: "Ilhas Cayman",
    iso3Code: "CYM",
  ),
  Country(
    isoCode: "CF",
    phoneCode: "236",
    name: "República Centro-Africana",
    iso3Code: "CAF",
  ),
  Country(
    isoCode: "TD",
    phoneCode: "235",
    name: "Chad",
    iso3Code: "TCD",
  ),
  Country(
    isoCode: "CL",
    phoneCode: "56",
    name: "Chile",
    iso3Code: "CHL",
  ),
  Country(
    isoCode: "CN",
    phoneCode: "86",
    name: "China",
    iso3Code: "CHN",
  ),
  Country(
    isoCode: "CX",
    phoneCode: "61",
    name: "Ilha Christmas",
    iso3Code: "CXR",
  ),
  Country(
    isoCode: "CC",
    phoneCode: "61",
    name: "Ilhas Cocos (Keeling)",
    iso3Code: "CCK",
  ),
  Country(
    isoCode: "CO",
    phoneCode: "57",
    name: "Colômbia",
    iso3Code: "COL",
  ),
  Country(
    isoCode: "KM",
    phoneCode: "269",
    name: "Comores",
    iso3Code: "COM",
  ),
  Country(
    isoCode: "CG",
    phoneCode: "242",
    name: "Congo",
    iso3Code: "COG",
  ),
  Country(
    isoCode: "CD",
    phoneCode: "243",
    name: "Congo, República Democrática do",
    iso3Code: "COD",
  ),
  Country(
    isoCode: "CK",
    phoneCode: "682",
    name: "Ilhas Cook",
    iso3Code: "COK",
  ),
  Country(
    isoCode: "CR",
    phoneCode: "506",
    name: "Costa Rica",
    iso3Code: "CRI",
  ),
  Country(
    isoCode: "HR",
    phoneCode: "385",
    name: "Croácia",
    iso3Code: "HRV",
  ),
  Country(
    isoCode: "CU",
    phoneCode: "53",
    name: "Cuba",
    iso3Code: "CUB",
  ),
  Country(
    isoCode: "CW",
    phoneCode: "599",
    name: "Curaçao",
    iso3Code: "CUW",
  ),
  Country(
    isoCode: "CY",
    phoneCode: "357",
    name: "Chipre",
    iso3Code: "CYP",
  ),
  Country(
    isoCode: "CZ",
    phoneCode: "420",
    name: "República Tcheca",
    iso3Code: "CZE",
  ),
  Country(
    isoCode: "CI",
    phoneCode: "225",
    name: "Côte d'Ivoire",
    iso3Code: "CIV",
  ),
  Country(
    isoCode: "DK",
    phoneCode: "45",
    name: "Dinamarca",
    iso3Code: "DNK",
  ),
  Country(
    isoCode: "DJ",
    phoneCode: "253",
    name: "Djibouti",
    iso3Code: "DJI",
  ),
  Country(
    isoCode: "DM",
    phoneCode: "1-767",
    name: "Dominica",
    iso3Code: "DMA",
  ),
  Country(
    isoCode: "DO",
    phoneCode: "1-849",
    name: "República Dominicana",
    iso3Code: "DOM",
  ),
  Country(
    isoCode: "EC",
    phoneCode: "593",
    name: "Equador",
    iso3Code: "ECU",
  ),
  Country(
    isoCode: "EG",
    phoneCode: "20",
    name: "Egito",
    iso3Code: "EGY",
  ),
  Country(
    isoCode: "SV",
    phoneCode: "503",
    name: "El Salvador",
    iso3Code: "SLV",
  ),
  Country(
    isoCode: "GB-ENG",
    phoneCode: "44",
    name: "Inglaterra",
    iso3Code: "GBR",
  ),
  Country(
    isoCode: "GQ",
    phoneCode: "240",
    name: "Guiné Equatorial",
    iso3Code: "GNQ",
  ),
  Country(
    isoCode: "ER",
    phoneCode: "291",
    name: "Eritreia",
    iso3Code: "ERI",
  ),
  Country(
    isoCode: "EE",
    phoneCode: "372",
    name: "Estônia",
    iso3Code: "EST",
  ),
  Country(
    isoCode: "ET",
    phoneCode: "251",
    name: "Etiópia",
    iso3Code: "ETH",
  ),
  Country(
    isoCode: "FK",
    phoneCode: "500",
    name: "Ilhas Falkland (Malvinas)",
    iso3Code: "FLK",
  ),
  Country(
    isoCode: "FO",
    phoneCode: "298",
    name: "Ilhas Faroé",
    iso3Code: "FRO",
  ),
  Country(
    isoCode: "FJ",
    phoneCode: "679",
    name: "Fiji",
    iso3Code: "FJI",
  ),
  Country(
    isoCode: "FI",
    phoneCode: "358",
    name: "Finlândia",
    iso3Code: "FIN",
  ),
  Country(
    isoCode: "FR",
    phoneCode: "33",
    name: "França",
    iso3Code: "FRA",
  ),
  Country(
    isoCode: "GF",
    phoneCode: "594",
    name: "Guiana Francesa",
    iso3Code: "GUF",
  ),
  Country(
    isoCode: "PF",
    phoneCode: "689",
    name: "Polinésia Francesa",
    iso3Code: "PYF",
  ),
  Country(
    isoCode: "TF",
    phoneCode: "262",
    name: "Territórios Franceses do Sul",
    iso3Code: "ATF",
  ),
  Country(
    isoCode: "GA",
    phoneCode: "241",
    name: "Gabão",
    iso3Code: "GAB",
  ),
  Country(
    isoCode: "GM",
    phoneCode: "220",
    name: "Gâmbia",
    iso3Code: "GMB",
  ),
  Country(
    isoCode: "GE",
    phoneCode: "995",
    name: "Georgia",
    iso3Code: "GEO",
  ),
  Country(
    isoCode: "DE",
    phoneCode: "49",
    name: "Alemanha",
    iso3Code: "DEU",
  ),
  Country(
    isoCode: "GH",
    phoneCode: "233",
    name: "Gana",
    iso3Code: "GHA",
  ),
  Country(
    isoCode: "GI",
    phoneCode: "350",
    name: "Gibraltar",
    iso3Code: "GIB",
  ),
  Country(
    isoCode: "GR",
    phoneCode: "30",
    name: "Grécia",
    iso3Code: "GRC",
  ),
  Country(
    isoCode: "GL",
    phoneCode: "299",
    name: "Groenlândia",
    iso3Code: "GRL",
  ),
  Country(
    isoCode: "GD",
    phoneCode: "1-473",
    name: "Grenada",
    iso3Code: "GRD",
  ),
  Country(
    isoCode: "GP",
    phoneCode: "590",
    name: "Guadalupe",
    iso3Code: "GLP",
  ),
  Country(
    isoCode: "GU",
    phoneCode: "1-671",
    name: "Guam",
    iso3Code: "GUM",
  ),
  Country(
    isoCode: "GT",
    phoneCode: "502",
    name: "Guatemala",
    iso3Code: "GTM",
  ),
  Country(
    isoCode: "GG",
    phoneCode: "44-1481",
    name: "Guernsey",
    iso3Code: "GGY",
  ),
  Country(
    isoCode: "GN",
    phoneCode: "224",
    name: "Guiné",
    iso3Code: "GIN",
  ),
  Country(
    isoCode: "GW",
    phoneCode: "245",
    name: "Guiné-Bissau",
    iso3Code: "GNB",
  ),
  Country(
    isoCode: "GY",
    phoneCode: "592",
    name: "Guiana",
    iso3Code: "GUY",
  ),
  Country(
    isoCode: "HT",
    phoneCode: "509",
    name: "Haiti",
    iso3Code: "HTI",
  ),
  Country(
    isoCode: "HM",
    phoneCode: "672",
    name: "Ilha Heard e Ilhas McDonald",
    iso3Code: "HMD",
  ),
  Country(
    isoCode: "VA",
    phoneCode: "379",
    name: "Santa Sé (Estado da Cidade do Vaticano)",
    iso3Code: "VAT",
  ),
  Country(
    isoCode: "HN",
    phoneCode: "504",
    name: "Honduras",
    iso3Code: "HND",
  ),
  Country(
    isoCode: "HK",
    phoneCode: "852",
    name: "Hong Kong",
    iso3Code: "HKG",
  ),
  Country(
    isoCode: "HU",
    phoneCode: "36",
    name: "Hungria",
    iso3Code: "HUN",
  ),
  Country(
    isoCode: "IS",
    phoneCode: "354",
    name: "Islândia",
    iso3Code: "ISL",
  ),
  Country(
    isoCode: "IN",
    phoneCode: "91",
    name: "Índia",
    iso3Code: "IND",
  ),
  Country(
    isoCode: "ID",
    phoneCode: "62",
    name: "Indonésia",
    iso3Code: "IDN",
  ),
  Country(
    isoCode: "IR",
    phoneCode: "98",
    name: "Irã, República Islâmica do",
    iso3Code: "IRN",
  ),
  Country(
    isoCode: "IQ",
    phoneCode: "964",
    name: "Iraque",
    iso3Code: "IRQ",
  ),
  Country(
    isoCode: "IE",
    phoneCode: "353",
    name: "Irlanda",
    iso3Code: "IRL",
  ),
  Country(
    isoCode: "IM",
    phoneCode: "44-1624",
    name: "Ilha de Man",
    iso3Code: "IMN",
  ),
  Country(
    isoCode: "IL",
    phoneCode: "972",
    name: "Israel",
    iso3Code: "ISR",
  ),
  Country(
    isoCode: "IT",
    phoneCode: "39",
    name: "Itália",
    iso3Code: "ITA",
  ),
  Country(
    isoCode: "JM",
    phoneCode: "1-876",
    name: "Jamaica",
    iso3Code: "JAM",
  ),
  Country(
    isoCode: "JP",
    phoneCode: "81",
    name: "Japão",
    iso3Code: "JPN",
  ),
  Country(
    isoCode: "JE",
    phoneCode: "44-1534",
    name: "Jersey",
    iso3Code: "JEY",
  ),
  Country(
    isoCode: "JO",
    phoneCode: "962",
    name: "Jordan",
    iso3Code: "JOR",
  ),
  Country(
    isoCode: "KZ",
    phoneCode: "7",
    name: "Cazaquistão",
    iso3Code: "KAZ",
  ),
  Country(
    isoCode: "KE",
    phoneCode: "254",
    name: "Quênia",
    iso3Code: "KEN",
  ),
  Country(
    isoCode: "KI",
    phoneCode: "686",
    name: "Kiribati",
    iso3Code: "KIR",
  ),
  Country(
    isoCode: "KP",
    phoneCode: "850",
    name: "Coreia, República Popular Democrática da",
    iso3Code: "PRK",
  ),
  Country(
    isoCode: "KR",
    phoneCode: "82",
    name: "Coreia, República da",
    iso3Code: "KOR",
  ),
  Country(
    isoCode: "XK",
    phoneCode: "383",
    name: "Kosovo",
    iso3Code: "KOS",
  ),
  Country(
    isoCode: "KW",
    phoneCode: "965",
    name: "Kuwait",
    iso3Code: "KWT",
  ),
  Country(
    isoCode: "KG",
    phoneCode: "996",
    name: "Quirguistão",
    iso3Code: "KGZ",
  ),
  Country(
    isoCode: "LA",
    phoneCode: "",
    name: "República Democrática Popular do Laos",
    iso3Code: "LAO",
  ),
  Country(
    isoCode: "LV",
    phoneCode: "371",
    name: "Letônia",
    iso3Code: "LVA",
  ),
  Country(
    isoCode: "LB",
    phoneCode: "961",
    name: "Líbano",
    iso3Code: "LBN",
  ),
  Country(
    isoCode: "LS",
    phoneCode: "266",
    name: "Lesoto",
    iso3Code: "LSO",
  ),
  Country(
    isoCode: "LR",
    phoneCode: "231",
    name: "Libéria",
    iso3Code: "LBR",
  ),
  Country(
    isoCode: "LY",
    phoneCode: "218",
    name: "Líbia",
    iso3Code: "LBY",
  ),
  Country(
    isoCode: "LI",
    phoneCode: "423",
    name: "Liechtenstein",
    iso3Code: "LIE",
  ),
  Country(
    isoCode: "LT",
    phoneCode: "370",
    name: "Lituânia",
    iso3Code: "LTU",
  ),
  Country(
    isoCode: "LU",
    phoneCode: "352",
    name: "Luxemburgo",
    iso3Code: "LUX",
  ),
  Country(
    isoCode: "MO",
    phoneCode: "853",
    name: "Macau",
    iso3Code: "MAC",
  ),
  Country(
    isoCode: "MK",
    phoneCode: "389",
    name: "Macedônia, Antiga República Iugoslava da",
    iso3Code: "MKD",
  ),
  Country(
    isoCode: "MG",
    phoneCode: "261",
    name: "Madagascar",
    iso3Code: "MDG",
  ),
  Country(
    isoCode: "MW",
    phoneCode: "265",
    name: "Malawi",
    iso3Code: "MWI",
  ),
  Country(
    isoCode: "MY",
    phoneCode: "60",
    name: "Malásia",
    iso3Code: "MYS",
  ),
  Country(
    isoCode: "MV",
    phoneCode: "960",
    name: "Maldivas",
    iso3Code: "MDV",
  ),
  Country(
    isoCode: "ML",
    phoneCode: "223",
    name: "Mali",
    iso3Code: "MLI",
  ),
  Country(
    isoCode: "MT",
    phoneCode: "356",
    name: "Malta",
    iso3Code: "MLT",
  ),
  Country(
    isoCode: "MH",
    phoneCode: "692",
    name: "Ilhas Marshall",
    iso3Code: "MHL",
  ),
  Country(
    isoCode: "MQ",
    phoneCode: "596",
    name: "Martinica",
    iso3Code: "MTQ",
  ),
  Country(
    isoCode: "MR",
    phoneCode: "222",
    name: "Mauritânia",
    iso3Code: "MRT",
  ),
  Country(
    isoCode: "MU",
    phoneCode: "230",
    name: "Maurício",
    iso3Code: "MUS",
  ),
  Country(
    isoCode: "YT",
    phoneCode: "262",
    name: "Mayotte",
    iso3Code: "MYT",
  ),
  Country(
    isoCode: "MX",
    phoneCode: "52",
    name: "México",
    iso3Code: "MEX",
  ),
  Country(
    isoCode: "FM",
    phoneCode: "691",
    name: "Micronésia, Estados Federados da",
    iso3Code: "FSM",
  ),
  Country(
    isoCode: "MD",
    phoneCode: "373",
    name: "Moldávia, República da",
    iso3Code: "MDA",
  ),
  Country(
    isoCode: "MC",
    phoneCode: "377",
    name: "Monaco",
    iso3Code: "MCO",
  ),
  Country(
    isoCode: "MN",
    phoneCode: "976",
    name: "Mongólia",
    iso3Code: "MNG",
  ),
  Country(
    isoCode: "ME",
    phoneCode: "382",
    name: "Montenegro",
    iso3Code: "MNE",
  ),
  Country(
    isoCode: "MS",
    phoneCode: "1-664",
    name: "Montserrat",
    iso3Code: "MSR",
  ),
  Country(
    isoCode: "MA",
    phoneCode: "212",
    name: "Marrocos",
    iso3Code: "MAR",
  ),
  Country(
    isoCode: "MZ",
    phoneCode: "258",
    name: "Moçambique",
    iso3Code: "MOZ",
  ),
  Country(
    isoCode: "MM",
    phoneCode: "95",
    name: "Mianmar",
    iso3Code: "MMR",
  ),
  Country(
    isoCode: "NA",
    phoneCode: "264",
    name: "Namíbia",
    iso3Code: "NAM",
  ),
  Country(
    isoCode: "NR",
    phoneCode: "674",
    name: "Nauru",
    iso3Code: "NRU",
  ),
  Country(
    isoCode: "NP",
    phoneCode: "977",
    name: "Nepal",
    iso3Code: "NPL",
  ),
  Country(
    isoCode: "NL",
    phoneCode: "31",
    name: "Holanda",
    iso3Code: "NLD",
  ),
  Country(
    isoCode: "AN",
    phoneCode: "599",
    name: "Antilhas Holandesas",
    iso3Code: "AN",
  ),
  Country(
    isoCode: "NC",
    phoneCode: "687",
    name: "Nova Caledônia",
    iso3Code: "NCL",
  ),
  Country(
    isoCode: "NZ",
    phoneCode: "64",
    name: "Nova Zelândia",
    iso3Code: "NZL",
  ),
  Country(
    isoCode: "NI",
    phoneCode: "505",
    name: "Nicarágua",
    iso3Code: "NIC",
  ),
  Country(
    isoCode: "NE",
    phoneCode: "227",
    name: "Níger",
    iso3Code: "NER",
  ),
  Country(
    isoCode: "NG",
    phoneCode: "234",
    name: "Nigéria",
    iso3Code: "NGA",
  ),
  Country(
    isoCode: "NU",
    phoneCode: "683",
    name: "Niue",
    iso3Code: "NIU",
  ),
  Country(
    isoCode: "NF",
    phoneCode: "672",
    name: "Ilha Norfolk",
    iso3Code: "NFK",
  ),
  Country(
    isoCode: "GB-NIR",
    phoneCode: "44",
    name: "Irlanda do Norte",
    iso3Code: "GBR",
  ),
  Country(
    isoCode: "MP",
    phoneCode: "1-670",
    name: "Ilhas Marianas do Norte",
    iso3Code: "MNP",
  ),
  Country(
    isoCode: "NÃO",
    phoneCode: "47",
    name: "Noruega",
    iso3Code: "NOR",
  ),
  Country(
    isoCode: "OM",
    phoneCode: "968",
    name: "Omã",
    iso3Code: "OMN",
  ),
  Country(
    isoCode: "PK",
    phoneCode: "92",
    name: "Paquistão",
    iso3Code: "PAK",
  ),
  Country(
    isoCode: "PW",
    phoneCode: "680",
    name: "Palau",
    iso3Code: "PLW",
  ),
  Country(
    isoCode: "PS",
    phoneCode: "970",
    name: "Palestina",
    iso3Code: "PSE",
  ),
  Country(
    isoCode: "PA",
    phoneCode: "507",
    name: "Panama",
    iso3Code: "PAN",
  ),
  Country(
    isoCode: "PG",
    phoneCode: "675",
    name: "Papua Nova Guiné",
    iso3Code: "PNG",
  ),
  Country(
    isoCode: "PY",
    phoneCode: "595",
    name: "Paraguai",
    iso3Code: "PRY",
  ),
  Country(
    isoCode: "PE",
    phoneCode: "51",
    name: "Peru",
    iso3Code: "PER",
  ),
  Country(
    isoCode: "PH",
    phoneCode: "63",
    name: "Filipinas",
    iso3Code: "PHL",
  ),
  Country(
    isoCode: "PN",
    phoneCode: "64",
    name: "Pitcairn",
    iso3Code: "PCN",
  ),
  Country(
    isoCode: "PL",
    phoneCode: "48",
    name: "Polônia",
    iso3Code: "POL",
  ),
  Country(
    isoCode: "PT",
    phoneCode: "351",
    name: "Portugal",
    iso3Code: "PRT",
  ),
  Country(
    isoCode: "PR",
    phoneCode: "1-787",
    name: "Puerto Rico",
    iso3Code: "PRI",
  ),
  Country(
    isoCode: "QA",
    phoneCode: "974",
    name: "Qatar",
    iso3Code: "QAT",
  ),
  Country(
    isoCode: "RO",
    phoneCode: "40",
    name: "Romênia",
    iso3Code: "ROU",
  ),
  Country(
    isoCode: "RU",
    phoneCode: "7",
    name: "Federação Russa",
    iso3Code: "RUS",
  ),
  Country(
    isoCode: "RW",
    phoneCode: "250",
    name: "Ruanda",
    iso3Code: "RWA",
  ),
  Country(
    isoCode: "RE",
    phoneCode: "262",
    name: "Reunião",
    iso3Code: "REU",
  ),
  Country(
    isoCode: "BL",
    phoneCode: "590",
    name: "São Bartolomeu",
    iso3Code: "BLM",
  ),
  Country(
    isoCode: "SH",
    phoneCode: "290",
    name: "Santa Helena, Ascensão e Tristão da Cunha",
    iso3Code: "SHN",
  ),
  Country(
    isoCode: "KN",
    phoneCode: "1-869",
    name: "São Cristóvão e Neves",
    iso3Code: "KNA",
  ),
  Country(
    isoCode: "LC",
    phoneCode: "1-758",
    name: "Santa Lúcia",
    iso3Code: "LCA",
  ),
  Country(
    isoCode: "MF",
    phoneCode: "590",
    name: "Saint Martin",
    iso3Code: "MAF",
  ),
  Country(
    isoCode: "PM",
    phoneCode: "508",
    name: "São Pedro e Miquelão",
    iso3Code: "SPM",
  ),
  Country(
    isoCode: "VC",
    phoneCode: "1-784",
    name: "São Vicente e Granadinas",
    iso3Code: "VCT",
  ),
  Country(
    isoCode: "WS",
    phoneCode: "685",
    name: "Samoa",
    iso3Code: "WSM",
  ),
  Country(
    isoCode: "SM",
    phoneCode: "378",
    name: "San Marino",
    iso3Code: "SMR",
  ),
  Country(
    isoCode: "ST",
    phoneCode: "239",
    name: "São Tomé e Príncipe",
    iso3Code: "STP",
  ),
  Country(
    isoCode: "SA",
    phoneCode: "966",
    name: "Arábia Saudita",
    iso3Code: "SAU",
  ),
  Country(
    isoCode: "GB-SCT",
    phoneCode: "44",
    name: "Escócia",
    iso3Code: "GBR",
  ),
  Country(
    isoCode: "SN",
    phoneCode: "221",
    name: "Senegal",
    iso3Code: "SEN",
  ),
  Country(
    isoCode: "RS",
    phoneCode: "381",
    name: "Sérvia",
    iso3Code: "SRB",
  ),
  Country(
    isoCode: "SC",
    phoneCode: "248",
    name: "Seychelles",
    iso3Code: "SYC",
  ),
  Country(
    isoCode: "SL",
    phoneCode: "232",
    name: "Serra Leoa",
    iso3Code: "SLE",
  ),
  Country(
    isoCode: "SG",
    phoneCode: "65",
    name: "Singapura",
    iso3Code: "SGP",
  ),
  Country(
    isoCode: "SX",
    phoneCode: "1-721",
    name: "Sint Maarten (parte holandesa)",
    iso3Code: "SXM",
  ),
  Country(
    isoCode: "SK",
    phoneCode: "421",
    name: "Eslováquia",
    iso3Code: "SVK",
  ),
  Country(
    isoCode: "SI",
    phoneCode: "386",
    name: "Eslovênia",
    iso3Code: "SVN",
  ),
  Country(
    isoCode: "SB",
    phoneCode: "677",
    name: "Ilhas Salomão",
    iso3Code: "SLB",
  ),
  Country(
    isoCode: "SO",
    phoneCode: "252",
    name: "Somália",
    iso3Code: "SOM",
  ),
  Country(
    isoCode: "ZA",
    phoneCode: "27",
    name: "África do Sul",
    iso3Code: "ZAF",
  ),
  Country(
    isoCode: "GS",
    phoneCode: "500",
    name: "Ilhas Geórgia do Sul e Sandwich do Sul",
    iso3Code: "SGS",
  ),
  Country(
    isoCode: "SS",
    phoneCode: "211",
    name: "Sudão do Sul",
    iso3Code: "SSD",
  ),
  Country(
    isoCode: "ES",
    phoneCode: "34",
    name: "Espanha",
    iso3Code: "ESP",
  ),
  Country(
    isoCode: "LK",
    phoneCode: "94",
    name: "Sri Lanka",
    iso3Code: "LKA",
  ),
  Country(
    isoCode: "SD",
    phoneCode: "249",
    name: "Sudão",
    iso3Code: "SDN",
  ),
  Country(
    isoCode: "SR",
    phoneCode: "597",
    name: "Suriname",
    iso3Code: "ON",
  ),
  Country(
    isoCode: "SJ",
    phoneCode: "47",
    name: "Ilhas Svalbard e Jan Mayen",
    iso3Code: "SJM",
  ),
  Country(
    isoCode: "SZ",
    phoneCode: "268",
    name: "Suazilândia",
    iso3Code: "SWZ",
  ),
  Country(
    isoCode: "SE",
    phoneCode: "46",
    name: "Suécia",
    iso3Code: "SWE",
  ),
  Country(
    isoCode: "CH",
    phoneCode: "41",
    name: "Suíça",
    iso3Code: "CHE",
  ),
  Country(
    isoCode: "SY",
    phoneCode: "963",
    name: "República Árabe Síria",
    iso3Code: "SYR",
  ),
  Country(
    isoCode: "TW",
    phoneCode: "886",
    name: "Taiwan",
    iso3Code: "TWN",
  ),
  Country(
    isoCode: "TJ",
    phoneCode: "992",
    name: "Tajiquistão",
    iso3Code: "TJK",
  ),
  Country(
    isoCode: "TZ",
    phoneCode: "255",
    name: "Tanzânia, República Unida da",
    iso3Code: "TZA",
  ),
  Country(
    isoCode: "TH",
    phoneCode: "66",
    name: "Tailândia",
    iso3Code: "THA",
  ),
  Country(
    isoCode: "TL",
    phoneCode: "670",
    name: "Timor-Leste",
    iso3Code: "TLS",
  ),
  Country(
    isoCode: "TG",
    phoneCode: "228",
    name: "Togo",
    iso3Code: "TGO",
  ),
  Country(
    isoCode: "TK",
    phoneCode: "690",
    name: "Tokelau",
    iso3Code: "TKL",
  ),
  Country(
    isoCode: "TO",
    phoneCode: "676",
    name: "Tonga",
    iso3Code: "TON",
  ),
  Country(
    isoCode: "TT",
    phoneCode: "1-868",
    name: "Trinidad e Tobago",
    iso3Code: "TTO",
  ),
  Country(
    isoCode: "TN",
    phoneCode: "216",
    name: "Tunísia",
    iso3Code: "TUN",
  ),
  Country(
    isoCode: "TR",
    phoneCode: "90",
    name: "Turquia",
    iso3Code: "TUR",
  ),
  Country(
    isoCode: "TM",
    phoneCode: "993",
    name: "Turcomenistão",
    iso3Code: "TKM",
  ),
  Country(
    isoCode: "TC",
    phoneCode: "1-649",
    name: "Ilhas Turks e Caicos",
    iso3Code: "TCA",
  ),
  Country(
    isoCode: "TV",
    phoneCode: "688",
    name: "Tuvalu",
    iso3Code: "TUV",
  ),
  Country(
    isoCode: "UG",
    phoneCode: "256",
    name: "Uganda",
    iso3Code: "UGA",
  ),
  Country(
    isoCode: "UA",
    phoneCode: "380",
    name: "Ucrânia",
    iso3Code: "UKR",
  ),
  Country(
    isoCode: "AE",
    phoneCode: "971",
    name: "Emirados Árabes Unidos",
    iso3Code: "SÃO",
  ),
  Country(
    isoCode: "GB",
    phoneCode: "44",
    name: "Reino Unido",
    iso3Code: "GBR",
  ),
  Country(
    isoCode: "US",
    phoneCode: "1",
    name: "Estados Unidos",
    iso3Code: "USA",
  ),
  Country(
    isoCode: "UY",
    phoneCode: "598",
    name: "Uruguai",
    iso3Code: "URY",
  ),
  Country(
    isoCode: "UM",
    phoneCode: "1",
    name: "Ilhas Menores Distantes dos EUA",
    iso3Code: "UMI",
  ),
  Country(
    isoCode: "UZ",
    phoneCode: "998",
    name: "Uzbequistão",
    iso3Code: "UZB",
  ),
  Country(
    isoCode: "VU",
    phoneCode: "678",
    name: "Vanuatu",
    iso3Code: "VUT",
  ),
  Country(
    isoCode: "VE",
    phoneCode: "58",
    name: "Venezuela, República Bolivariana da",
    iso3Code: "VEN",
  ),
  Country(
    isoCode: "VN",
    phoneCode: "84",
    name: "Vietnã",
    iso3Code: "VNM",
  ),
  Country(
    isoCode: "VG",
    phoneCode: "1-284",
    name: "Ilhas Virgens Britânicas",
    iso3Code: "VGB",
  ),
  Country(
    isoCode: "VI",
    phoneCode: "1-340",
    name: "Ilhas Virgens, EUA",
    iso3Code: "VIR",
  ),
  Country(
    isoCode: "GB-WLS",
    phoneCode: "44",
    name: "País de Gales",
    iso3Code: "GBR",
  ),
  Country(
    isoCode: "WF",
    phoneCode: "681",
    name: "Ilhas Wallis e Futuna",
    iso3Code: "WLF",
  ),
  Country(
    isoCode: "EH",
    phoneCode: "212",
    name: "Saara Ocidental",
    iso3Code: "ESH",
  ),
  Country(
    isoCode: "YE",
    phoneCode: "967",
    name: "Iêmen",
    iso3Code: "YEM",
  ),
  Country(
    isoCode: "ZM",
    phoneCode: "260",
    name: "Zâmbia",
    iso3Code: "ZMB",
  ),
  Country(
    isoCode: "ZW",
    phoneCode: "263",
    name: "Zimbábue",
    iso3Code: "ZWE",
  ),
  Country(
    isoCode: "AX",
    phoneCode: "358",
    name: "Ilhas Åland",
    iso3Code: "ALA",
  ),
];
